function f_ss = autogen_drift_vector_field(I_bw,I_fw,dtheta_bw,dtheta_fw,dtheta_com,dx_com,dy_com,g,m_bw,m_com,m_fw,theta_bw,theta_fw)
%AUTOGEN_DRIFT_VECTOR_FIELD
%    F_SS = AUTOGEN_DRIFT_VECTOR_FIELD(I_BW,I_FW,DTHETA_BW,DTHETA_FW,DTHETA_COM,DX_COM,DY_COM,G,M_BW,M_COM,M_FW,THETA_BW,THETA_FW)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-May-2020 21:27:55

t2 = g.*m_bw;
t3 = g.*m_com;
t4 = g.*m_fw;
t5 = m_bw.*m_fw;
t6 = dx_com.^2;
t7 = dy_com.^2;
t8 = m_com.*2.0;
t9 = m_com.^2;
t10 = theta_bw.*2.0;
t11 = theta_fw.*2.0;
t12 = cos(t10);
t13 = cos(t11);
t14 = m_bw.*t8;
t15 = m_fw.*t8;
t16 = sin(t10);
t17 = sin(t11);
t18 = -t11;
t19 = m_com.*t8;
t20 = m_bw.*t12;
t21 = m_fw.*t13;
t22 = m_bw.*t16;
t23 = m_fw.*t17;
t24 = t10+t18;
t25 = cos(t24);
t26 = dtheta_bw.*dx_com.*t20.*2.0;
t27 = dtheta_fw.*dx_com.*t21.*2.0;
t28 = dtheta_bw.*dy_com.*t20.*2.0;
t29 = dtheta_fw.*dy_com.*t21.*2.0;
t30 = dtheta_bw.*dx_com.*t22.*2.0;
t31 = dtheta_fw.*dx_com.*t23.*2.0;
t32 = dtheta_bw.*dy_com.*t22.*2.0;
t33 = dtheta_fw.*dy_com.*t23.*2.0;
t37 = t22+t23;
t34 = -t30;
t35 = -t31;
t36 = t5.*t25;
t42 = t2+t3+t4+t26+t27+t32+t33;
t38 = -t36;
t41 = t28+t29+t34+t35;
t39 = t5+t14+t15+t19+t38;
t40 = 1.0./t39;
f_ss = [dx_com;dy_com;dtheta_com;dtheta_bw;dtheta_fw;-t40.*t41.*(m_bw+m_fw+t8-t20-t21)+t37.*t40.*t42;t37.*t40.*t41-t40.*t42.*(m_bw+m_fw+t8+t20+t21);0.0;(m_bw.*(-t6.*t16+t7.*t16+dx_com.*dy_com.*t12.*2.0))./I_bw;(m_fw.*(-t6.*t17+t7.*t17+dx_com.*dy_com.*t13.*2.0))./I_fw];
