function G = autogen_grav_vector(g,m_bw,m_com,m_fw)
%AUTOGEN_GRAV_VECTOR
%    G = AUTOGEN_GRAV_VECTOR(G,M_BW,M_COM,M_FW)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-May-2020 21:27:53

G = [0.0;g.*(m_bw+m_com+m_fw);0.0;0.0;0.0];
