%% inv_mass_matrix.m
%
% Description:
%   Wrapper function for autogen_inverse_mass_matrix.m
%   Computes the mass matrix of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   Minv: a 5x5 inverse mass matrix for the robot.

function Minv = inv_mass_matrix(x,params)

theta_com = x(3);
I_bw = params.model.dyn.bw.I;
I_com = params.model.dyn.com.I;
I_fw = params.model.dyn.fw.I;
m_bw = params.model.dyn.bw.m;
m_com = params.model.dyn.com.m;
m_fw = params.model.dyn.fw.m;
bw_com_distance = params.model.geom.bw_com.l;
bw_com_init_angle = params.model.geom.bw_com.theta;

bw_fw_distance = params.model.geom.bw_fw.l;

Minv = autogen_inverse_mass_matrix(I_bw,I_com,I_fw,bw_fw_distance,bw_com_distance,bw_com_init_angle,m_bw,m_com,m_fw,theta_com);

end

