function M = autogen_mass_matrix(I_bw,I_com,I_fw,m_bw,m_com,m_fw,theta_bw,theta_fw)
%AUTOGEN_MASS_MATRIX
%    M = AUTOGEN_MASS_MATRIX(I_BW,I_COM,I_FW,M_BW,M_COM,M_FW,THETA_BW,THETA_FW)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-May-2020 14:56:47

t2 = sin(theta_bw);
t3 = sin(theta_fw);
t4 = theta_bw.*2.0;
t5 = theta_fw.*2.0;
t6 = sin(t4);
t7 = sin(t5);
t8 = t2.^2;
t9 = t3.^2;
t10 = m_bw.*t8;
t11 = m_fw.*t9;
t12 = (m_bw.*t6)./2.0;
t13 = (m_fw.*t7)./2.0;
t14 = t12+t13;
M = reshape([m_bw+m_com+m_fw-t10-t11,t14,0.0,0.0,0.0,t14,m_com+t10+t11,0.0,0.0,0.0,0.0,0.0,I_com,0.0,0.0,0.0,0.0,0.0,I_bw,0.0,0.0,0.0,0.0,0.0,I_fw],[5,5]);
