function H = autogen_H_eom(bw_com_distance,bw_com_init_angle,dtheta_com,fw_com_distance,fw_com_init_angle,g,m_bw,m_com,m_fw,theta_com)
%AUTOGEN_H_EOM
%    H = AUTOGEN_H_EOM(BW_COM_DISTANCE,BW_COM_INIT_ANGLE,DTHETA_COM,FW_COM_DISTANCE,FW_COM_INIT_ANGLE,G,M_BW,M_COM,M_FW,THETA_COM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-May-2020 10:06:56

t2 = bw_com_init_angle+theta_com;
t3 = fw_com_init_angle+theta_com;
t4 = cos(t2);
t5 = cos(t3);
H = [dtheta_com.^2.*(bw_com_distance.*m_bw.*t4+fw_com_distance.*m_fw.*t5);dtheta_com.*(bw_com_distance.*dtheta_com.*m_bw.*sin(t2)+dtheta_com.*fw_com_distance.*m_fw.*sin(t3))+g.*(m_bw+m_com+m_fw);-bw_com_distance.*g.*m_bw.*t4-fw_com_distance.*g.*m_fw.*t5;0.0;0.0];
