function [A_all,H_bw_x,H_bw_y,H_fw_y,H_fw_bw,H_fw_ramp,H_bw_ramp] = autogen_constraint_derivatives(bw_fw_distance,r_bw,r_fw,theta_com,x_bf,x_ramp,y_bf,y_ramp)
%AUTOGEN_CONSTRAINT_DERIVATIVES
%    [A_ALL,H_BW_X,H_BW_Y,H_FW_Y,H_FW_BW,H_FW_RAMP,H_BW_RAMP] = AUTOGEN_CONSTRAINT_DERIVATIVES(BW_FW_DISTANCE,R_BW,R_FW,THETA_COM,X_BF,X_RAMP,Y_BF,Y_RAMP)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2020 16:59:40

t2 = cos(theta_com);
t3 = sin(theta_com);
t4 = bw_fw_distance.*t2;
t5 = x_bf.*2.0;
t6 = y_bf.*2.0;
t7 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
t8 = bw_fw_distance.*t3;
t9 = bw_fw_distance.*t3.*2.0;
t10 = bw_fw_distance.*t2.*2.0;
t11 = bw_fw_distance.^2;
t12 = t8+y_bf-y_ramp;
t13 = t4+x_bf-x_ramp;
A_all = reshape([1.0,0.0,0.0,0.0,t5+t10-x_ramp.*2.0,t5-x_ramp.*2.0,0.0,1.0,1.0,0.0,t6+t9-y_ramp.*2.0,t6-y_ramp.*2.0,0.0,0.0,t4,0.0,bw_fw_distance.*t2.*t12.*2.0-bw_fw_distance.*t3.*t13.*2.0,0.0,r_bw,0.0,0.0,r_bw,0.0,0.0,0.0,0.0,0.0,-r_fw,0.0,0.0],[6,5]);
if nargout > 1
    H_bw_x = t7;
end
if nargout > 2
    H_bw_y = t7;
end
if nargout > 3
    H_fw_y = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 4
    H_fw_bw = t7;
end
if nargout > 5
    H_fw_ramp = reshape([2.0,0.0,-t9,0.0,0.0,0.0,2.0,t10,0.0,0.0,-t9,t10,t2.^2.*t11.*2.0+t3.^2.*t11.*2.0-bw_fw_distance.*t2.*t13.*2.0-bw_fw_distance.*t3.*t12.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 6
    H_bw_ramp = reshape([2.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
