function M = autogen_mass_matrix(I_bw,I_com,I_fw,bw_fw_distance,bw_com_distance,bw_com_init_angle,m_bw,m_com,m_fw,theta_com)
%AUTOGEN_MASS_MATRIX
%    M = AUTOGEN_MASS_MATRIX(I_BW,I_COM,I_FW,BW_FW_DISTANCE,BW_COM_DISTANCE,BW_COM_INIT_ANGLE,M_BW,M_COM,M_FW,THETA_COM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-May-2020 23:48:22

t2 = cos(theta_com);
t3 = sin(theta_com);
t4 = bw_com_init_angle+theta_com;
t6 = m_bw+m_com+m_fw;
t5 = cos(t4);
t7 = sin(t4);
t8 = bw_fw_distance.*m_fw.*t2;
t9 = bw_fw_distance.*m_fw.*t3;
t10 = -t9;
t11 = bw_com_distance.*m_com.*t5;
t12 = bw_com_distance.*m_com.*t7;
t13 = -t12;
t14 = t8+t11;
t15 = t10+t13;
M = reshape([t6,0.0,t15,0.0,0.0,0.0,t6,t14,0.0,0.0,t15,t14,I_com+bw_com_distance.^2.*m_com+bw_fw_distance.^2.*m_fw,0.0,0.0,0.0,0.0,0.0,I_bw,0.0,0.0,0.0,0.0,0.0,I_fw],[5,5]);
