function Minv = autogen_inverse_mass_matrix(I_bw,I_com,I_fw,m_bw,m_com,m_fw,theta_bw,theta_fw)
%AUTOGEN_INVERSE_MASS_MATRIX
%    MINV = AUTOGEN_INVERSE_MASS_MATRIX(I_BW,I_COM,I_FW,M_BW,M_COM,M_FW,THETA_BW,THETA_FW)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-May-2020 14:56:48

t2 = m_bw.*m_fw;
t3 = m_com.*2.0;
t4 = m_com.^2;
t5 = theta_bw.*2.0;
t6 = theta_fw.*2.0;
t7 = cos(t5);
t8 = cos(t6);
t9 = m_bw.*t3;
t10 = m_fw.*t3;
t11 = sin(t5);
t12 = sin(t6);
t13 = -t6;
t14 = m_com.*t3;
t15 = m_bw.*t7;
t16 = m_fw.*t8;
t17 = m_bw.*t11;
t18 = m_fw.*t12;
t19 = t5+t13;
t20 = cos(t19);
t22 = t17+t18;
t21 = t2.*t20;
t23 = -t21;
t24 = t2+t9+t10+t14+t23;
t25 = 1.0./t24;
t26 = t22.*t25;
t27 = -t26;
Minv = reshape([t25.*(m_bw+m_fw+t3-t15-t16),t27,0.0,0.0,0.0,t27,t25.*(m_bw+m_fw+t3+t15+t16),0.0,0.0,0.0,0.0,0.0,1.0./I_com,0.0,0.0,0.0,0.0,0.0,1.0./I_bw,0.0,0.0,0.0,0.0,0.0,1.0./I_fw],[5,5]);
