function [A_all,H_bw_x,H_bw_y,H_fw_y,H_fw_bw] = autogen_constraint_derivatives(bw_fw_distance,r_bw,r_fw,theta_com)
%AUTOGEN_CONSTRAINT_DERIVATIVES
%    [A_ALL,H_BW_X,H_BW_Y,H_FW_Y,H_FW_BW] = AUTOGEN_CONSTRAINT_DERIVATIVES(BW_FW_DISTANCE,R_BW,R_FW,THETA_COM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-May-2020 17:06:40

A_all = reshape([1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,bw_fw_distance.*cos(theta_com),0.0,r_bw,0.0,0.0,r_bw,0.0,0.0,0.0,-r_fw],[4,5]);
if nargout > 1
    H_bw_x = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 2
    H_bw_y = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 3
    H_fw_y = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-bw_fw_distance.*sin(theta_com),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 4
    H_fw_bw = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
