function Minv = autogen_inverse_mass_matrix(I_bw,I_com,I_fw,m_bw,m_com,m_fw,theta_bw,theta_fw)
%AUTOGEN_INVERSE_MASS_MATRIX
%    MINV = AUTOGEN_INVERSE_MASS_MATRIX(I_BW,I_COM,I_FW,M_BW,M_COM,M_FW,THETA_BW,THETA_FW)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-May-2020 12:39:04

t2 = theta_bw.*2.0;
t3 = theta_fw.*2.0;
t4 = m_bw.*m_com.*2.0;
t5 = m_bw.*m_fw;
t6 = m_com.*m_fw.*2.0;
t7 = m_com.^2;
t8 = t7.*2.0;
t9 = t2-t3;
t10 = cos(t9);
t18 = m_bw.*m_fw.*t10;
t11 = t4+t5+t6+t8-t18;
t12 = 1.0./t11;
t13 = sin(t2);
t14 = m_bw.*t13;
t15 = sin(t3);
t16 = m_fw.*t15;
t17 = t14+t16;
t19 = m_com.*2.0;
t20 = cos(t2);
t21 = cos(t3);
Minv = reshape([t12.*(m_bw+m_fw+t19-m_bw.*t20-m_fw.*t21),-t12.*t17,0.0,0.0,0.0,-t12.*t17,t12.*(m_bw+m_fw+t19+m_bw.*t20+m_fw.*t21),0.0,0.0,0.0,0.0,0.0,1.0./I_com,0.0,0.0,0.0,0.0,0.0,1.0./I_bw,0.0,0.0,0.0,0.0,0.0,1.0./I_fw],[5,5]);
