function M = autogen_mass_matrix(I_bw,I_com,I_fw,bw_fw_distance,bw_com_distance,bw_com_init_angle,m_bw,m_com,m_fw,theta_com)
%AUTOGEN_MASS_MATRIX
%    M = AUTOGEN_MASS_MATRIX(I_BW,I_COM,I_FW,BW_FW_DISTANCE,BW_COM_DISTANCE,BW_COM_INIT_ANGLE,M_BW,M_COM,M_FW,THETA_COM)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Jun-2020 21:04:20

t2 = m_bw+m_com+m_fw;
t3 = bw_com_init_angle+theta_com;
t4 = sin(theta_com);
t5 = sin(t3);
t6 = -bw_com_distance.*m_com.*t5-bw_fw_distance.*m_fw.*t4;
t7 = cos(theta_com);
t8 = bw_fw_distance.*m_fw.*t7;
t9 = cos(t3);
t10 = bw_com_distance.*m_com.*t9;
t11 = t8+t10;
M = reshape([t2,0.0,t6,0.0,0.0,0.0,t2,t11,0.0,0.0,t6,t11,I_com+bw_com_distance.^2.*m_com+bw_fw_distance.^2.*m_fw,0.0,0.0,0.0,0.0,0.0,I_bw,0.0,0.0,0.0,0.0,0.0,I_fw],[5,5]);
