function C_all = autogen_constraints(bw_com_distance,bw_com_init_angle,fw_com_distance,fw_com_init_angle,r_bw,r_fw,theta_bw,theta_fw,theta_com,x_com,y_com)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(BW_COM_DISTANCE,BW_COM_INIT_ANGLE,FW_COM_DISTANCE,FW_COM_INIT_ANGLE,R_BW,R_FW,THETA_BW,THETA_FW,THETA_COM,X_COM,Y_COM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-May-2020 10:06:51

t2 = r_bw.*theta_bw;
t3 = -r_bw;
C_all = [t2+x_com;t3+y_com-bw_com_distance.*sin(bw_com_init_angle+theta_com);t3+y_com-fw_com_distance.*sin(fw_com_init_angle+theta_com);t2-r_fw.*theta_fw];
