function C_all = autogen_constraints(bw_fw_distance,r_bw,r_fw,r_ramp,theta_bw,theta_fw,theta_com,x_bf,x_ramp,y_bf,y_ramp)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(BW_FW_DISTANCE,R_BW,R_FW,R_RAMP,THETA_BW,THETA_FW,THETA_COM,X_BF,X_RAMP,Y_BF,Y_RAMP)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-May-2020 22:52:41

t2 = r_bw.*theta_bw;
t3 = x_bf-x_ramp;
t4 = y_bf-y_ramp;
t5 = x_bf-x_ramp+bw_fw_distance.*cos(theta_com);
t6 = sin(theta_com);
t7 = bw_fw_distance.*t6;
t8 = t7+y_bf-y_ramp;
t9 = r_ramp.^2;
C_all = [t2+x_bf;-r_bw+y_bf;-r_bw+t7+y_bf;t2-r_fw.*theta_fw;-t9+t3.^2+t4.^2;-t9+t5.^2+t8.^2];
