function H = autogen_H_eom(bw_fw_distance,bw_com_distance,bw_com_init_angle,dtheta_com,g,m_bw,m_com,m_fw,theta_com)
%AUTOGEN_H_EOM
%    H = AUTOGEN_H_EOM(BW_FW_DISTANCE,BW_COM_DISTANCE,BW_COM_INIT_ANGLE,DTHETA_COM,G,M_BW,M_COM,M_FW,THETA_COM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-May-2020 17:06:42

t2 = cos(theta_com);
t3 = bw_com_init_angle+theta_com;
t4 = cos(t3);
H = [-dtheta_com.^2.*(bw_com_distance.*m_com.*t4+bw_fw_distance.*m_fw.*t2);-dtheta_com.*(bw_com_distance.*dtheta_com.*m_com.*sin(t3)+bw_fw_distance.*dtheta_com.*m_fw.*sin(theta_com))+g.*(m_bw+m_com+m_fw);bw_com_distance.*g.*m_com.*t4+bw_fw_distance.*g.*m_fw.*t2;0.0;0.0];
