function C_all = autogen_constraints(bw_com_distance,bw_com_init_angle,fw_com_distance,fw_com_init_angle,r_bw,theta_bw,theta_com,x_com,y_com)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(BW_COM_DISTANCE,BW_COM_INIT_ANGLE,FW_COM_DISTANCE,FW_COM_INIT_ANGLE,R_BW,THETA_BW,THETA_COM,X_COM,Y_COM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-May-2020 15:54:47

t2 = cos(theta_com);
t3 = sin(theta_com);
t6 = -r_bw;
t4 = t2.^2;
t5 = t3.^2;
t7 = t4+t5;
C_all = [x_com+t6.*theta_bw;t6+y_com-bw_com_distance.*t7.*sin(bw_com_init_angle+theta_com);t6+y_com-fw_com_distance.*t7.*sin(fw_com_init_angle+theta_com)];
