%% drift_vector_field.m
%
% Description:
%   Wrapper function for autogen_drift_vector_field.m
%   Computes the drift vector field for the nonlinear state-space
%   dynamics of the cart-pendulum robot.
%
% Inputs:
%   x: the state vector, x = [x_cart; theta_pend; dx_cart; dtheta_pend];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   f_ss: a 10x1 vector that maps state x to dx (time derivative of
%       the state x) when control input u = 0.

function f_ss = drift_vector_field(x,params)

theta_bw = x(4);
theta_fw = x(5);
dx_com = x(6);
dy_com = x(7);
dtheta_com = x(8);
dtheta_bw = x(9);
dtheta_fw = x(10);

%function f_ss = autogen_drift_vector_field(I_bw,I_fw,dtheta_bw,dtheta_fw,dtheta_com,dx_com,dy_com,g,m_bw,m_com,m_fw,theta_bw,theta_fw)

f_ss = autogen_drift_vector_field(params.model.dyn.bw.I,...
                                  params.model.dyn.fw.I,...
                                  dtheta_bw,...
                                  dtheta_fw,...
                                  dtheta_com,...
                                  dx_com,...
                                  dy_com,...
                                  params.model.dyn.g,...
                                  params.model.dyn.bw.m,...
                                  params.model.dyn.com.m,...
                                  params.model.dyn.fw.m,...
                                  theta_bw,...
                                  theta_fw);
end