function Energy = autogen_energy(I_bike,I_mw,dtheta_mw,dtheta_bike,g,l_com,m_bike,m_mw,theta_bike)
%AUTOGEN_ENERGY
%    ENERGY = AUTOGEN_ENERGY(I_BIKE,I_MW,DTHETA_MW,DTHETA_BIKE,G,L_COM,M_BIKE,M_MW,THETA_BIKE)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-May-2020 13:20:10

t2 = dtheta_bike.^2;
t3 = l_com.^2;
Energy = (I_mw.*t2)./2.0+(I_mw.*dtheta_mw.^2)./2.0+(t2.*(I_bike+m_bike.*t3))./2.0+I_mw.*dtheta_mw.*dtheta_bike+(m_mw.*t2.*t3)./2.0+g.*l_com.*sin(theta_bike).*(m_bike+m_mw);
