%% inv_mass_matrix.m
%
% Description:
%   Wrapper function for autogen_inverse_mass_matrix.m
%   Computes the mass matrix of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   Minv: a 5x5 inverse mass matrix for the robot.

function Minv = inv_mass_matrix(x,params)
theta_bike = x(1);

I_bike =  params.model.dyn.com.I;
l_com = params.model.dyn.com.l;
I_mw = params.model.dyn.mw.I;
m_mw = params.model.dyn.mw.m;
m_bike = params.model.dyn.com.m;
offset = params.model.dyn.mw.offset;

Minv = autogen_inverse_mass_matrix(I_bike,I_mw,l_com,m_bike,m_mw);

end

