function g_ss = autogen_control_vector_field(m_bw,m_com,m_fw,theta_bw,theta_fw)
%AUTOGEN_CONTROL_VECTOR_FIELD
%    G_SS = AUTOGEN_CONTROL_VECTOR_FIELD(M_BW,M_COM,M_FW,THETA_BW,THETA_FW)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-May-2020 21:27:55

t2 = m_bw.*m_fw;
t3 = m_com.^2;
t4 = theta_bw.*2.0;
t5 = theta_fw.*2.0;
t6 = m_bw.*m_com.*2.0;
t7 = m_com.*m_fw.*2.0;
t8 = -t5;
t9 = t3.*2.0;
t10 = t4+t8;
t11 = cos(t10);
t12 = t2.*t11;
t13 = -t12;
t14 = t2+t6+t7+t9+t13;
t15 = 1.0./t14;
g_ss = [0.0;0.0;0.0;0.0;0.0;t15.*(m_bw+m_com.*2.0+m_fw-m_bw.*cos(t4)-m_fw.*cos(t5));-t15.*(m_bw.*sin(t4)+m_fw.*sin(t5));0.0;0.0;0.0];
