function [A_all,H_bw_x,H_bw_y,H_fw_y,H_fw_bw,H_bw_ramp,H_fw_ramp,H_uphill_fw,H_uphill_bw,H_hill_fw,H_hill_bw,H_downhill_fw,H_downhill_bw] = autogen_constraint_derivatives(bw_fw_distance,r_bw,r_fw,theta_com,x_bf,x_ramp,y_bf,y_ramp)
%AUTOGEN_CONSTRAINT_DERIVATIVES
%    [A_ALL,H_BW_X,H_BW_Y,H_FW_Y,H_FW_BW,H_BW_RAMP,H_FW_RAMP,H_UPHILL_FW,H_UPHILL_BW,H_HILL_FW,H_HILL_BW,H_DOWNHILL_FW,H_DOWNHILL_BW] = AUTOGEN_CONSTRAINT_DERIVATIVES(BW_FW_DISTANCE,R_BW,R_FW,THETA_COM,X_BF,X_RAMP,Y_BF,Y_RAMP)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Jun-2020 21:04:18

t2 = x_bf.*2.0;
t3 = cos(theta_com);
t4 = y_bf.*2.0;
t5 = sin(theta_com);
t6 = bw_fw_distance.*t3;
t7 = bw_fw_distance.*t5;
t8 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
t9 = bw_fw_distance.*t5.*2.0;
t10 = bw_fw_distance.*t3.*2.0;
t11 = bw_fw_distance.^2;
t12 = t7+y_bf-y_ramp;
t13 = t6+x_bf-x_ramp;
t14 = t6-t7;
A_all = reshape([1.0,0.0,0.0,0.0,t2-x_ramp.*2.0,t2+t10-x_ramp.*2.0,-1.0,-1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,t4-y_ramp.*2.0,t4+t9-y_ramp.*2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,t6,0.0,0.0,bw_fw_distance.*t3.*t12.*2.0-bw_fw_distance.*t5.*t13.*2.0,t6+t7,0.0,t6,0.0,t14,0.0,r_bw,0.0,0.0,r_bw,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-r_fw,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[12,5]);
if nargout > 1
    H_bw_x = t8;
end
if nargout > 2
    H_bw_y = t8;
end
if nargout > 3
    t15 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
    H_fw_y = t15;
end
if nargout > 4
    H_fw_bw = t8;
end
if nargout > 5
    H_bw_ramp = reshape([2.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 6
    H_fw_ramp = reshape([2.0,0.0,-t9,0.0,0.0,0.0,2.0,t10,0.0,0.0,-t9,t10,t3.^2.*t11.*2.0+t5.^2.*t11.*2.0-bw_fw_distance.*t3.*t13.*2.0-bw_fw_distance.*t5.*t12.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 7
    H_uphill_fw = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 8
    H_uphill_bw = t8;
end
if nargout > 9
    H_hill_fw = t15;
end
if nargout > 10
    H_hill_bw = t8;
end
if nargout > 11
    H_downhill_fw = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t6-t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 12
    H_downhill_bw = t8;
end
