function C_all = autogen_constraints(l_com,theta_bike)
%AUTOGEN_CONSTRAINTS
%    C_ALL = AUTOGEN_CONSTRAINTS(L_COM,THETA_BIKE)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-May-2020 13:20:11

t2 = cos(theta_bike);
t3 = l_com.^2;
t4 = sin(theta_bike);
C_all = -t3+t2.^2.*t3+t3.*t4.^2;
