function Minv = autogen_inverse_mass_matrix(I_bike,I_mw,l_com,m_bike,m_mw)
%AUTOGEN_INVERSE_MASS_MATRIX
%    MINV = AUTOGEN_INVERSE_MASS_MATRIX(I_BIKE,I_MW,L_COM,M_BIKE,M_MW)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    29-May-2020 13:54:49

t2 = l_com.^2;
t3 = m_bike.*t2;
t4 = m_mw.*t2;
t5 = I_bike+t3+t4;
t6 = 1.0./t5;
Minv = reshape([t6,-t6,-t6,(t6.*(I_bike+I_mw+t3+t4))./I_mw],[2,2]);
