%% H_eom.m
%
% Description:
%   Wrapper function for autogen_H.m
%   Computes H(q,q_dot) for the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   H: a 5x1 set of terms.

function H = H_eom(x,params)

theta_bike = x(1);
dtheta_bike = x(3);

g = params.model.dyn.g;
m_bike = params.model.dyn.com.m;
l_com = params.model.dyn.com.l;
m_mw =  params.model.dyn.mw.m;
offset = params.model.dyn.mw.offset;

%function H = autogen_H_eom(theta_bike,g,m_bike,l_com)
H = autogen_H_eom(dtheta_bike,g,l_com,m_bike,m_mw,offset,theta_bike);

end

